project:
  type: website
  output-dir: docs

website:
  title: "MEF MGMT 553 Spring 2022-2023"
  navbar:
    left:
      - href: index.qmd
        text: Main Page

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



