---
title: "MEF MGMT 553 Bahar 2022-2023"
toc: false
---

+ [Projeler](./proje.html)

# Ders 7 (24 Mayıs 2023)

+ Sunumlar!

# Ders 6 (17 Mayıs 2023)

+ Misafir hoca: [Barış Balta](https://www.linkedin.com/in/barisbalta/) Sufle Teknoloji Kurucu Ortağı, AWS Ambassador
+ Bulut Bilişim
    + [Türkçe Kaynak](https://www.youtube.com/watch?v=zn5W1Hk-FFI)

# Ders 5 (10 Mayıs 2023)

+ Misafir hoca: [Erdem Sezer](https://www.linkedin.com/in/sezererdem/) Kalkınma Yatırım Bankası Sektörel Araştırma Kıdemli Başkan Yardımcısı
+ Makine Öğrenmesi (devam)
+ Ürün Geliştirme / Ürün Yönetimi
    + [Türkçe Kaynak](https://www.youtube.com/watch?v=iUI81e5juX0) | [Türkçe Kaynak 2](https://www.youtube.com/watch?v=irGNHrRxssM)


# Ders 4 (3 Mayıs 2023)

+ Misafir hoca: [Onur Karadeli](https://www.linkedin.com/in/onur-karadeli-phd-c-a46a59112/) İleri Analitik, RPA ve Büyük Veri Müdürü, Socar Türkiye
+ Konu: Makine Öğrenmesi, Yapay Zeka ve Optimizasyon Giriş
    + Optimizasyon Giriş
        + [Kaynak](https://or-primer.github.io/)
        + [Ek Kaynak](https://www.youtube.com/watch?v=w9BlUqa2JpI)
        + [Türkçe Kaynak](https://www.youtube.com/watch?v=D7_DHhpIF4M) | [Türkçe Kaynak 2](https://www.youtube.com/watch?v=B2FZR_4bElE)
    + Makine Öğrenmesi ve Yapay Zeka Giriş
        + [Multi Armed Bandits](./bandits_notes.html)
            + [Türkçe Kaynak](https://yz-ai.github.io/blog/pekistirmeli-ogrenme/cok-kollu-haydutlar-bolum-2)
        + [Makine Öğrenmesi Giriş - 1](./intro_ml_1.html) | [Makine Öğrenmesi Giriş - 2](./intro_ml_2.html)
            + [Türkçe Kaynak - Çoklu Doğrusal Regresyon](https://www.youtube.com/watch?v=xgbSdcZ4X-g)
            + [Türkçe Kaynak - Makine Öğrenmesi](https://www.youtube.com/watch?v=HBvMz7GTfv0)
            + [Türkçe Kaynak - Karar Ağaçları](https://www.youtube.com/watch?v=vCysce2PKzc)
        + [Ek Kaynak](https://www.statlearning.com/)

# Ders 3 (26 Nisan 2023)

+ Konu: Dinamik Raporlama ([Quarto](https://quarto.org/docs/guide/) / [RMarkdown](https://rmarkdown.rstudio.com/))
    + [Ek Kaynak](https://www.youtube.com/watch?v=yvi5uXQMvu4)
    + [Türkçe Kaynak](https://medium.com/@mustafacavus/quarto-yeni-nesil-dinamik-r-python-ve-julia-raporlama-arac%C4%B1-3d6705e61c37)
    + [Türkçe Kaynak 2 - RMarkdown](https://www.datasciencearth.com/r-markdown-ile-dinamik-raporlama/)
+ Konu 2: Dashboard oluşturma ([Shiny](https://shiny.rstudio.com/))
    + [Türkçe Kaynak](https://www.youtube.com/watch?v=uLpmMD_PJEM)
+ Serbest Uygulama: [YÖK Yabancı Öğrenci Verisi](https://github.com/berkorbay/datasets/raw/master/foreign_students/foreign_students_by_nationality_2021_2022.xlsx) 
    + [Başlangıç Kodu](https://gist.github.com/berkorbay/f394bf2ea8775cf7b5316aeafd27c482#file-foreign_students_report_starter_code-qmd)


# Ders 2 (19 Nisan 2023)

+ Misafir hoca: [Burak Yitgin](https://www.linkedin.com/in/burakyitgin/) EPİAŞ Strateji Geliştirme Kıdemli Uzmanı ve Akademisyen (Sabancı Üniversitesi - Enerji Teknolojileri ve Yönetimi YL)
+ Konu: Veri Düzenleme ve Görselleştirme
    + dplyr: [Kaynak](https://berkorbay.github.io/book-of-eda/dplyr.html) - [Ek kaynak](https://www.youtube.com/watch?v=bzrP5bOIyYI)
    + ggplot2: [Kaynak](https://berkorbay.github.io/book-of-eda/ggplot2.html) - [Ek kaynak](https://www.youtube.com/watch?v=QB8OXAzL8QE)
+ Serbest Uygulama: [YÖK Yabancı Öğrenci Verisi](https://github.com/berkorbay/datasets/raw/master/foreign_students/foreign_students_by_nationality_2021_2022.xlsx) 
    + [Başlangıç Kodu](https://gist.github.com/berkorbay/f394bf2ea8775cf7b5316aeafd27c482#file-foreign_students_starter_code-r)
    

# Ders 1 (12 Nisan 2023)

+ [Giriş](./intro.html)
+ Ödev 1: Tanışma (Blackboard)
+ Uygulama: [Startup Deals 2021](https://github.com/berkorbay/datasets/raw/master/startup_deals/startup_deals_2021.xlsx)
    + Excel üzerinde bu veriyi inceleyip düzenleyip bir "rapor" hazırlayın
    + Rapor Powerpoint formatında olsun max 5 sayfa

Ek kaynak:

+ [MEF BDA 503](https://mef-bda503.github.io/fall22/)
+ [Eskişehir R User Group](https://www.youtube.com/@eskisehirrusergroup2103)


This class is supported by [Datacamp for Universities](https://www.datacamp.com/universities#classroom-form). Students will learn from interactive environments in their journeys as data analysts and data scientists.