---
title: Tanışma ve Giriş
subtitle: MEF MGMT 553 (Bahar 2022-2023)
author: Berk Orbay
format: 
    revealjs:
        smaller: true
---

## Dersin amaçları

Bu dersin üç ana amacı bulunmaktadır.

- Temel veri analiz ve veri bilimi yetkinliklerini aktarmak
- Veri bilimi ile ilgili ileri düzey çalışmalar konusunda bilgilendirmek
- Katılımcıların bu derste gördükleri ve öğrendiklerini kendi kurumlarındaki süreçlere çevik bir şekilde entegre edebilmelerini sağlamak

Bu amaçlara ulaşmak doğrultusunda her hafta

- Veri bilimi konusunda teknik bir konu işlenecektir
- Sektörden misafir hocalar ile farklı sektörlerdeki ileri düzey konular hakkında bilgilendirme sağlanacaktır
- Ders içi uygulamalar ile öğrenilenler pekiştirilecektir

Dersin sonunda öğrencilerin iş hayatlarında veri bilimi projelerini uygulayabilecekleri bir çerçeve yöntemin nosyonunu ve ihtiyaç duydukları gerekli araçları nasıl kullanabileceklerini öğrenmeleri hedeflenmektedir.

## Ders programı

Haftalık tahmini program aşağıdaki gibidir. Değişiklikler olabilir.

1. Tanışma ve veri analitiğine giriş
2. Veri düzenleme ve görselleştirme
3. Otomatik Raporlama 
4. Modelleme (Optimizasyon / Makine Öğrenmesi / Yapay Zeka)
5. Ürün Geliştirme
6. Bulut Bilişim
7. Sunumlar

2. hafta ve 6. hafta arasında dersimize misafir hocaların katılması hedeflenmektedir.

## Derse Katılım ve Değerlendirme

Derse katılım Zoom üzerinden gerçekleştirilecektir.

Değerlendirme için aşağıdaki yöntemler kullanılacaktır.

- Ödevler: Kısa ve öğrenciyi araştırmaya veya katılıma yönlendirecek veri odaklı görevler.
    - Veri anketi (%10)
    - Datacamp (Introduction to Tidyverse) (%20)
    - Yöneylem Araştırması Ödevi (%10)
- Sınıf içi uygulamalar: Öğrencilerin kendi uzmanlık alanlarıyla, veri bilimi temellerini birleştirebilecekleri kısa süreli görevler. (%10)
- Derse katılım: Derste veri odaklı tartışmalara katılım ve misafir hocalar ile etkileşim (%10)
- Datacamp: Ders dışında teknik yetkinlikleri pekiştirme   
- **Proje** (%50)

Toplam 110 puan + Bonuslar


## Grup Projesi

+ Grupların oluşturulması (5-6 kişilik gruplar)  
+ Grup belirleme son tarih: 26 Nisan Çarşamba 23:59  
    + Grup ismi ve üyelerinin mail yoluyla bildirilmeli  
    + Son tarihe kadar gruplar oluşturulmadığı takdirde rastgele atama yapılacaktır  
+ Grup proje dökümanının Blackboard'a yüklenmesi  
+ 7. hafta sunumlar  

Grup projeleri sektörel bir problem üzerinde yapılan bir araştırma, bir veri analizi ve çözüm önerilerinden oluşan bir sunum şeklinde yapılacaktır. Detaylar 2. hafta açıklanacaktır.

## Etik

Verimli ve adil bir ders deneyimi için çok basit kurallarımız bulunuyor.

1. Lütfen sınıf arkadaşlarınız ile **beraber çalışın.**
2. Lütfen internet ve diğer kaynakları çözüm bulmak için kullanın. Arada bir bu dersteki ödevler ve projeler hakkında çözümler bulma ihtimaliniz var ancak öğrenmek veya basitçe kopyala yapıştır yapmak size kalmış.
3. Lütfen **sadece kopyala yapıştır yapmayın** ve her zaman **faydalandığınız kaynakları belirtin**. Örneğin, "Bu linkteki görselleştirme tekniğini çok beğendim ve projemde uyguladım" her zaman için kabul edilebilir ve hatta istenen bir şeydir. 

Ancak "Kaggle'da birinin yaptığı analizi boylu boyunca kopyalayıp yapıştırdım ve ödev olarak teslim ettim" demek kabul edilemez. Doğrudan F alma sebebidir.

4. Lütfen arkadaşlarınız ile **bire bir aynı ödevi teslim etmeyin**. Birbirinizin çalışmasından faydalanıyor olsanız dahi; aynı kodu ve aynı analizi, aynı cümleler ile vermeyin.

## Misafir Hocalar

2. hafta ile 6. hafta arasında her hafta bir misafir hoca dersimize katılacak. Tahmini program aşağıdaki gibi gerçekleşecektir. Değişiklikler olabilir.
 
+ [Burak Yitgin](https://www.linkedin.com/in/burakyitgin/) - EPİAŞ Strateji Geliştirme / Sabancı Üniv Enerji Piyasaları 
+ [Erdem Sezer](https://www.linkedin.com/in/sezererdem/) -  Kalkınma Yatırım Bankası Sektörel Araştırma
+ [Onur Karadeli](https://www.linkedin.com/in/onur-karadeli-phd-c-a46a59112/) - SOCAR İleri Analitik
+ (Yakında)
+ [Gizem Gür](https://www.linkedin.com/in/gizemgur/) - Sufle AWS Advanced Tier Partner


## Veride el kirletme

+ [Gerekli olabilecek programlar](https://mef-bda503.github.io/fall22/intro.html#/which-tools-are-we-going-to-use-programs)
+ [Book of EDA](https://berkorbay.github.io/book-of-eda/)
+ [Posit Cloud](https://posit.cloud/)
+ [Google Colab](https://colab.research.google.com/)

## Faydalı Kaynaklar

+ [MEF BDA 503](https://mef-bda503.github.io/fall22/)  
+ [OR Primer](https://or-primer.github.io/)  
+ [Introduction to Statistical Learning](https://statlearning.com/)  
+ [Datacamp](https://datacamp.com)
+ [Hugging Face](https://huggingface.co/)